/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import BusinessModel.Manager;
import Model.Adherent;
import Model.AdherentImage;
import Model.Person;
import Model.PoliticalParty;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
 

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import net.sourceforge.tess4j.ITesseract;
import net.sourceforge.tess4j.Tesseract1;
/**
 *
 * @author Andrea
 */
public class adherentListi extends javax.swing.JFrame {
 MyTableModel validModel;
 MyTableModel1 rejectedModel;
 MyTableModel3 deleteModel;
 MyTableModel2 banModel;
    /**
    /**
     * Creates new form adherentListi
     */
    long id;
    String name;
    int signaturesVal;
    boolean primera_etapa;
    static int count;
    
    public adherentListi() {

        initComponents();
        validModel = new MyTableModel();
	tableValidated.setModel(validModel);
        rejectedModel = new MyTableModel1();
	tableRechazados.setModel(rejectedModel);
        deleteModel = new MyTableModel3();
	jTable4.setModel(deleteModel);
         banModel = new MyTableModel2();
	jTable5.setModel(banModel);
    }
    
    public adherentListi(long idParty,String nameParty) {
        java.lang.System.out.println(java.lang.System.getProperty("os.name"));
        File dll;
        if(java.lang.System.getProperty("os.name").equals("Linux")){
            dll = new File("lib/libopencv_java2412.so");
        }else{
            dll = new File("lib/opencv_java2412.dll");
        }
                
        java.lang.System.load(dll.getAbsolutePath());
        initComponents();
        id = idParty;
        name = nameParty;
        int amountNotValidated = Manager.queryAmountAdherentImageNoValidatedbyPartyId(id);
        txtAmount.setText(""+amountNotValidated);
        validModel = new MyTableModel();
	tableValidated.setModel(validModel);
        rejectedModel = new MyTableModel1();
	tableRechazados.setModel(rejectedModel);
        deleteModel = new MyTableModel3();
	jTable4.setModel(deleteModel);
         banModel = new MyTableModel2();
	jTable5.setModel(banModel);
        primera_etapa = true;//checkStage(idParty); Retorna "0" si es etapa 1 de validación, "1" si es etapa 2 de validación
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        paneAnulados = new javax.swing.JTabbedPane();
        jPaneSinValidar = new javax.swing.JPanel();
        btnValidate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        validateConsole = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        validateProgressBar = new javax.swing.JProgressBar();
        jButton3 = new javax.swing.JButton();
        jPaneValidados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableValidated = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jPaneRechazados = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableRechazados = new javax.swing.JTable();
        btnAnalizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jPaneAnulados = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jPaneBaneados = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setTitle("Lista de adherente - Proceso Electoral Municipal 2016");

        jLabel1.setText("Cantidad restante:");

        btnValidate.setText("Validar");
        btnValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidateActionPerformed(evt);
            }
        });

        jLabel2.setText("Cantidad:");

        txtAmount.setEditable(false);
        txtAmount.setBackground(new java.awt.Color(204, 204, 204));
        txtAmount.setText("0");
        txtAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        validateConsole.setEditable(false);
        validateConsole.setBackground(new java.awt.Color(204, 204, 204));
        validateConsole.setColumns(20);
        validateConsole.setRows(5);
        jScrollPane3.setViewportView(validateConsole);

        jLabel4.setText("Progreso:");

        validateProgressBar.setToolTipText("");

        jButton3.setText("Reporte");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneSinValidarLayout = new javax.swing.GroupLayout(jPaneSinValidar);
        jPaneSinValidar.setLayout(jPaneSinValidarLayout);
        jPaneSinValidarLayout.setHorizontalGroup(
            jPaneSinValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneSinValidarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneSinValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPaneSinValidarLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(51, 51, 51)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addGroup(jPaneSinValidarLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(validateProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPaneSinValidarLayout.setVerticalGroup(
            jPaneSinValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneSinValidarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPaneSinValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneSinValidarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jButton3))
                    .addComponent(btnValidate, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validateProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        paneAnulados.addTab("Sin Validar", jPaneSinValidar);

        tableValidated.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableValidated);
        if (tableValidated.getColumnModel().getColumnCount() > 0) {
            tableValidated.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel3.setText("Cantidad:");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton5.setText("Reporte");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneValidadosLayout = new javax.swing.GroupLayout(jPaneValidados);
        jPaneValidados.setLayout(jPaneValidadosLayout);
        jPaneValidadosLayout.setHorizontalGroup(
            jPaneValidadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneValidadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneValidadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(jPaneValidadosLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(50, 50, 50)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(jSeparator3))
                .addContainerGap())
        );
        jPaneValidadosLayout.setVerticalGroup(
            jPaneValidadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneValidadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneValidadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneAnulados.addTab("Validados", jPaneValidados);

        tableRechazados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido", "Firma", "Huella"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableRechazados);

        btnAnalizar.setText("Analizar Adherente");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad:");

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(204, 204, 204));

        jButton4.setText("Reporte");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneRechazadosLayout = new javax.swing.GroupLayout(jPaneRechazados);
        jPaneRechazados.setLayout(jPaneRechazadosLayout);
        jPaneRechazadosLayout.setHorizontalGroup(
            jPaneRechazadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneRechazadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneRechazadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneRechazadosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(51, 51, 51)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAnalizar)))
                .addContainerGap())
        );
        jPaneRechazadosLayout.setVerticalGroup(
            jPaneRechazadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneRechazadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneRechazadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnalizar)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneAnulados.addTab("Rechazados", jPaneRechazados);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido", "Firma", "Huella"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable4);

        jLabel6.setText("Cantidad:");

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(204, 204, 204));

        jButton7.setText("Reporte");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneAnuladosLayout = new javax.swing.GroupLayout(jPaneAnulados);
        jPaneAnulados.setLayout(jPaneAnuladosLayout);
        jPaneAnuladosLayout.setHorizontalGroup(
            jPaneAnuladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneAnuladosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneAnuladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneAnuladosLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(51, 51, 51)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPaneAnuladosLayout.setVerticalGroup(
            jPaneAnuladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneAnuladosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneAnuladosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        paneAnulados.addTab("Anulados", jPaneAnulados);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable5);

        jLabel7.setText("Cantidad:");

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(204, 204, 204));

        jButton9.setText("Reporte");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneBaneadosLayout = new javax.swing.GroupLayout(jPaneBaneados);
        jPaneBaneados.setLayout(jPaneBaneadosLayout);
        jPaneBaneadosLayout.setHorizontalGroup(
            jPaneBaneadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneBaneadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPaneBaneadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneBaneadosLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(51, 51, 51)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPaneBaneadosLayout.setVerticalGroup(
            jPaneBaneadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneBaneadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneBaneadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        paneAnulados.addTab("Baneados", jPaneBaneados);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneAnulados)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneAnulados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FileOutputStream archivo;
        try {
            archivo = new FileOutputStream("ReporteRechazados.pdf");
            Document documento = new Document();
            PdfWriter.getInstance(documento, archivo);
            documento.open();
            documento.add(new Paragraph("Reporte de Rechazados"));
            documento.add(new Paragraph("DNI        Nombre          Apellido Paterno        Apellido Materno     "));
            /*     for (int i =0; i<listSales.size();i++){
                Sales s = listSales.get(i);
                Customer cus = null;
                if (s.getCustomer() instanceof Person){
                    cus = (Person)s.getCustomer();
                    documento.add(new Paragraph(""+ listSales.get(i).getId() + " " + ((Person)s.getCustomer()).getName()+ " " + s.getTotal() + " "+ s.getDetails().size() ));
                }
                else{
                    cus = (Company)s.getCustomer();
                    documento.add(new Paragraph(""+ listSales.get(i).getId() + " " + ((Company)s.getCustomer()).getName()+ " " + s.getTotal() + " "+ s.getDetails().size() ));
                }
            }*/
            documento.close();
        } catch (FileNotFoundException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        } catch (DocumentException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        int row = tableRechazados.getSelectedRow();
        if(row != -1){
            long idSource = Long.parseLong( (String) tableRechazados.getValueAt(row, 0));
            String dniSource = (String) tableRechazados.getValueAt(row, 1);
            String nameSource = (String) tableRechazados.getValueAt(row, 2);
            String lastnameSource = (String) tableRechazados.getValueAt(row, 3);
            String signatureSource = (String) tableRechazados.getValueAt(row, 4);
            String fingerprintSource = (String) tableRechazados.getValueAt(row, 5);            
            addAdherent frame = new addAdherent(id, idSource, name, dniSource, nameSource, lastnameSource, signatureSource, fingerprintSource);
            frame.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Debe elegir un registro rechazado", "Alerta", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        FileOutputStream archivo;
        try {
            archivo = new FileOutputStream("ReporteValidados.pdf");
            Document documento = new Document();
            PdfWriter.getInstance(documento, archivo);
            documento.open();
            String titulo="Reporte de Lista Validada del Partido " + name;
            documento.add(new Paragraph(titulo));
            String cuerpo="Se encontraron validas "+signaturesVal+" firmas";
            documento.add(new Paragraph(cuerpo));
            //documento.add(new Paragraph("DNI        Nombre          Apellido Paterno        Apellido Materno     "));
            /*     for (int i =0; i<listSales.size();i++){
                Sales s = listSales.get(i);
                Customer cus = null;
                if (s.getCustomer() instanceof Person){
                    cus = (Person)s.getCustomer();
                    documento.add(new Paragraph(""+ listSales.get(i).getId() + " " + ((Person)s.getCustomer()).getName()+ " " + s.getTotal() + " "+ s.getDetails().size() ));
                }
                else{
                    cus = (Company)s.getCustomer();
                    documento.add(new Paragraph(""+ listSales.get(i).getId() + " " + ((Company)s.getCustomer()).getName()+ " " + s.getTotal() + " "+ s.getDetails().size() ));
                }
            }*/
            documento.close();
            JOptionPane.showMessageDialog(this, "Reporte creado!", "Mensaje", JOptionPane.WARNING_MESSAGE);
        } catch (FileNotFoundException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        } catch (DocumentException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:jskdkdsjkjds
        FileOutputStream archivo;
        try {
            archivo = new FileOutputStream("ReporteSinValidar.pdf");
            Document documento = new Document();
            PdfWriter.getInstance(documento, archivo);
            String titulo="Reporte de Lista Sin Validar del Partido " + name;
            documento.open();
            documento.add(new Paragraph(titulo));
            documento.add(new Paragraph("DNI        Nombre          Apellido Paterno        Apellido Materno     "));

            /*     for (int i =0; i<listSales.size();i++){
                Sales s = listSales.get(i);
                Customer cus = null;
                if (s.getCustomer() instanceof Person){
                    cus = (Person)s.getCustomer();
                    documento.add(new Paragraph(""+ listSales.get(i).getId() + " " + ((Person)s.getCustomer()).getName()+ " " + s.getTotal() + " "+ s.getDetails().size() ));
                }
                else{
                    cus = (Company)s.getCustomer();
                    documento.add(new Paragraph(""+ listSales.get(i).getId() + " " + ((Company)s.getCustomer()).getName()+ " " + s.getTotal() + " "+ s.getDetails().size() ));
                }
            }*/
            documento.close();
        } catch (FileNotFoundException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        } catch (DocumentException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private boolean check_route(long id){
        String filePathString= "test/auxiliar/cortes/"+id;
        File f = new File(filePathString);
        return f.exists() && f.isDirectory();
    }
    
    private void btnValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidateActionPerformed
        FingerprintLib.console = validateConsole;
        FingerprintLib.status = validateProgressBar;
        
        PoliticalParty partido = Manager.queryPoliticalPartyById(id);
        if(Manager.getSession().getId() == partido.getIdWorker()){
            if (check_route(partido.getId())){
                ArrayList<AdherentImage> registros = Manager.queryAdherentImageNoValidatedbyPartyId(partido.getId());
                ITesseract instance_num = new Tesseract1();
                ITesseract instance_let = new Tesseract1();
                instance_num.setTessVariable("tessedit_char_whitelist", "0123456789");
                instance_let.setTessVariable("tessedit_char_whitelist", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz");
                int cantidad = registros.size();
                count = 0;
                java.lang.System.out.println("Cantidad de archivos: " + cantidad);
                validateProgressBar.setValue(0);
                for (AdherentImage registro : registros) {
                    validateConsole.append("\nInterpretando imagenes via OCR");
                    validateConsole.update(validateConsole.getGraphics());
                    Person persona = ocrLib.ocr(this, instance_num, instance_let, registro.getDniSource(), registro.getNameSource(), registro.getLastNameSource());
                    if(persona != null){
                        boolean isSuitable = UtilLib.isSuitable(persona, partido.getElectoralProcess().getId());
                        if(isSuitable==false){ // para continuar flujo. sino quitar el FALSE
                            long party_id = UtilLib.findDuplicity(persona, partido.getElectoralProcess().getId());
                            if(party_id == -1){
                                validateConsole.append("\nValidando Huellas");
                                validateConsole.update(validateConsole.getGraphics());
                                double puntuacion1 = FingerprintLib.huellas(persona.getFingerprint(), registro.getFingerprintSource());
                                validateConsole.append("\nValidando Firmas");
                                validateConsole.update(validateConsole.getGraphics());
                                double puntuacion2 = SignatureLib.validarFirmas(persona.getSignature(), registro.getSignatureSource());
                                //boolean resultado = analizar_resultado(puntuacion1, puntuacion2);
                                boolean resultado = true; //para continuar flujo
                                if(resultado){
                                    java.lang.System.out.println("Se pudo validar a esta persona");
                                    validateConsole.append("\nSe pudo validar a esta persona");
                                    validateConsole.update(validateConsole.getGraphics());
                                    Adherent ad = new Adherent();
                                    ad.setDni(persona.getDni()); ad.setName(persona.getName());
                                    ad.setLastName(persona.getLastname()); ad.setObservation("Validado");                                    
                                    ad.setPoliticalParty(partido);
                                    Manager.addAdherent(ad);
                                    UtilLib.deleteImages(registro);
                                    Manager.deleteAdherentImage(registro.getId()); 
                                }else{
                                    java.lang.System.out.println("No se pudo validar a esta persona");
                                    validateConsole.append("\nNo se pudo validar a esta persona");
                                    validateConsole.update(validateConsole.getGraphics());
                                    if(primera_etapa){
                                        registro.setStatus(1);                                        
                                        Manager.updateAdherentImage(registro);
                                    }else{
                                        Manager.deleteAdherentImage(registro.getId()); 
                                    }                                    
                                }
                            }else{
                                java.lang.System.out.println("Se encontro duplicidad referida a esta persona");
                                validateConsole.append("\nSe encontro duplicidad referida a esta persona");
                                validateConsole.update(validateConsole.getGraphics());
                                if(primera_etapa){
                                    Adherent ad = Manager.queryAdherentByDniAndPoliticalParty(persona.getDni(), party_id);
                                    ad.setObservation("Duplicado");
                                    Manager.updateStatusAdherent(ad);                                    
                                }
                                UtilLib.deleteImages(registro);
                                Manager.deleteAdherentImage(registro.getId()); 
                            }
                        }else{
                            java.lang.System.out.println("Esta persona no pertenece al ubigeo, o no esta en condiciones de ejercer la ciudadania");
                            validateConsole.append("\nEsta persona no pertenece al ubigeo, o no esta en condiciones de ejercer la ciudadania");
                            validateConsole.update(validateConsole.getGraphics());
                            UtilLib.deleteImages(registro);
                            Manager.deleteAdherentImage(registro.getId()); 
                        }
                    }else{
                        java.lang.System.out.println("No se pudo determinar quien es esta persona");
                        validateConsole.append("\nNo se pudo determinar quien es esta persona");
                        validateConsole.update(validateConsole.getGraphics());
                        if(primera_etapa){
                            registro.setStatus(1);
                            Manager.updateAdherentImage(registro);
                        }else{
                            UtilLib.deleteImages(registro);
                            Manager.deleteAdherentImage(registro.getId()); 
                        }
                    }
                    count++;
                    int porcentaje = (100*count)/cantidad;
                    java.lang.System.out.println("Porcentaje: " + porcentaje);
                    validateProgressBar.setValue(porcentaje);
                    validateProgressBar.update(validateProgressBar.getGraphics());
                    refreshTblAdherent();
                }
                
                JOptionPane.showMessageDialog(this, "Se termino de validar al partido, podra apreciar los resultados en las pestañas correspondientes", "Resultado", JOptionPane.OK_OPTION);
            }else{
                JOptionPane.showMessageDialog(this, "No existe la ruta de los cortes para este partido", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "El trabajador no esta asignado para este partido politico", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
        /*
        Estados encontrados: 0 - Sin validar, 1 - rechazado, 2 - anulado.
        */

        /*
        String filePathString= "test\\auxiliar\\cortes\\"+id+"\\padron";
        File f = new File(filePathString);
        if(f.exists() && !f.isDirectory()) {
            SignatureLib.console=jTextArea1;
            signaturesVal=validarFirmas(id);
        }else{
            JOptionPane.showMessageDialog(this, "No se han procesado los padrones", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
        */
    }//GEN-LAST:event_btnValidateActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

   
         class MyTableModel extends AbstractTableModel {
        ArrayList<Model.Adherent> userList = Manager.queryAllAdherents(id);
		String [] titles = {"Id","DNI", "Nombre","Apellido"};
		public int getColumnCount() {
			// TODO Auto-generated method stub
			return 4;
		}

		public int getRowCount() {
			// TODO Auto-generated method stub
			return userList.size();
		}

		public Object getValueAt(int row, int col) {
			// TODO Auto-generated method stub
			String value = "";
			switch (col) {
                        case 0:
				value = "" + userList.get(row).getId();
				break;
			case 1:
				value = "" + userList.get(row).getDni();
				break;
			case 2:
                                value = "" + userList.get(row).getName();
				break;
			case 3:
				value = "" + userList.get(row).getLastName();
				break;	
			}
			return value;
		}
		public String getColumnName(int col){
			return titles[col];
		}
    }
     class MyTableModel1 extends AbstractTableModel {
         
        ArrayList<Model.AdherentImage> userList = Manager.queryAllAdherentImagesRejected(id);
		String [] titles = {"id", "DNI", "Nombre","Apellido","Firma", "Huella"};
		public int getColumnCount() {
			// TODO Auto-generated method stub
			return 6;
		}

		public int getRowCount() {
			// TODO Auto-generated method stub
			return userList.size();
		}

		public Object getValueAt(int row, int col) {
			// TODO Auto-generated method stub
			String value = "";
			switch (col) {
                        case 0:
				value = "" + userList.get(row).getId();
				break;
			case 1:
				value = "" + userList.get(row).getDniSource();
				break;
			case 2:
                                value = "" + userList.get(row).getNameSource();
				break;
			case 3:
				value = "" + userList.get(row).getLastNameSource();
				break;	
                        case 4:
				value = "" + userList.get(row).getSignatureSource();
				break;	
                        case 5:
				value = "" + userList.get(row).getFingerprintSource();
				break;	
 
			}
			return value;
		}
		public String getColumnName(int col){
			return titles[col];
		}
    }     
         class MyTableModel2 extends AbstractTableModel {
          ArrayList<Model.Adherent> userList = Manager.queryAllAdherentsDuplicated(id);
		String [] titles
                            = {"Id","DNI", "Nombre","Apellido"};
		public int getColumnCount() {
			// TODO Auto-generated method stub
			return 4;
		}

		public int getRowCount() {
			// TODO Auto-generated method stub
			return userList.size();
		}

		public Object getValueAt(int row, int col) {
			// TODO Auto-generated method stub
			String value = "";
			switch (col) {
                        case 0:
				value = "" + userList.get(row).getId();
				break;
			case 1:
				value = "" + userList.get(row).getDni();
				break;
			case 2:
                                value = "" + userList.get(row).getName();
				break;
			case 3:
				value = "" + userList.get(row).getLastName();
				break;	
			}
			return value;
		}
		public String getColumnName(int col){
			return titles[col];
		}
    }
     class MyTableModel3 extends AbstractTableModel {
         ArrayList<Model.AdherentImage> userList = Manager.queryAllAdherentImagesCanceled(id);
		String [] titles = {"Id", "DNI", "Nombre","Apellido","Firma", "Huella"};
		public int getColumnCount() {
			// TODO Auto-generated method stub
			return 6;
		}

		public int getRowCount() {
			// TODO Auto-generated method stub
			return userList.size();
		}

		public Object getValueAt(int row, int col) {
			// TODO Auto-generated method stub
			String value = "";
			switch (col) {
                        case 0:
				value = "" + userList.get(row).getId();
				break;
			case 1:
				value = "" + userList.get(row).getDniSource();
				break;
			case 2:
                                value = "" + userList.get(row).getNameSource();
				break;
			case 3:
				value = "" + userList.get(row).getLastNameSource();
				break;	
                        case 4:
				value = "" + userList.get(row).getSignatureSource();
				break;	
                        case 5:
				value = "" + userList.get(row).getFingerprintSource();
				break;	
 
			}
			return value;
		}
		public String getColumnName(int col){
			return titles[col];
		}
    }     
    public void refreshTblAdherent() {
		validModel.userList = Manager.queryAllAdherents(id);
		validModel.fireTableChanged(null);
                rejectedModel.userList = Manager.queryAllAdherentImagesRejected(id);
		rejectedModel.fireTableChanged(null);
                deleteModel.userList = Manager.queryAllAdherentImagesCanceled(id);
		deleteModel.fireTableChanged(null);
                banModel.userList = Manager.queryAllAdherentsDuplicated(id);
		banModel.fireTableChanged(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnValidate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPaneAnulados;
    private javax.swing.JPanel jPaneBaneados;
    private javax.swing.JPanel jPaneRechazados;
    private javax.swing.JPanel jPaneSinValidar;
    private javax.swing.JPanel jPaneValidados;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTabbedPane paneAnulados;
    private javax.swing.JTable tableRechazados;
    private javax.swing.JTable tableValidated;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextArea validateConsole;
    private javax.swing.JProgressBar validateProgressBar;
    // End of variables declaration//GEN-END:variables
}
