/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JFrame;
import java.rmi.RemoteException;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.rmi.RemoteException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import Model.Ubigeo;
import Model.ElectoralProcess;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdatepicker.*;
import javax.swing.*;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;
import javax.swing.ComboBoxModel;
import Model.*;
import BusinessModel.Manager;
import static BusinessModel.Manager.addElectoralProcess;
import static BusinessModel.Manager.deleteElectoralProcess;
import static BusinessModel.Manager.updateElectoralProcess;
import java.awt.Component;
import javax.swing.JInternalFrame;
import javax.swing.table.AbstractTableModel;
/**
 *
 * @author 
 */
public class ElectoralProcessGui extends JFrame {
 MyTableModel electoralProcessModel;
    Long ElectoralProcessId;
    /**
     * Creates new form ElectoralProcess
     */
    public ElectoralProcessGui(Integer processId) {
        ElectoralProcessId=Long.parseLong(processId.toString());
        initComponents();
        electoralProcessModel = new MyTableModel();
	jTable1.setModel(electoralProcessModel);
        
        ElectoralProcess p = Manager.queryElectoralProcessById(ElectoralProcessId);

        jTextField9.setText("" + p.getId());
        jTextField1.setText(p.getName());
        jTextField3.setText(""+p.getPopulation());
        jTextField8.setText(""+p.getMinPercentage());
        jComboBox1.setSelectedItem(p.getProcessType());        
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");                                                                
        jTextField2.setText(""+ formatter.format(p.getDate()));
        jTextField5.setText(""+formatter.format(p.getStartRegistrationDate()));
        jTextField4.setText(""+formatter.format(p.getEndRegistrationDate()));
        jTextField7.setText(""+formatter.format(p.getStartValidationDate()));
        jTextField6.setText(""+formatter.format(p.getEndValidationDate()));
        jTextField10.setText(""+formatter.format(p.getStartExtraReceptionDate()));
        jTextField12.setText(""+formatter.format(p.getStartExtraValidationDate()));
        jTextField14.setText(""+formatter.format(p.getStartReceptionDate()));
        jTextField11.setText(""+formatter.format(p.getEndExtraReceptionDate()));
        jTextField13.setText(""+formatter.format(p.getEndExtraValidationDate()));
        jTextField15.setText(""+formatter.format(p.getEndReceptionDate()));
    }
    
     public ElectoralProcessGui() {
        initComponents();
        electoralProcessModel = new MyTableModel();
	jTable1.setModel(electoralProcessModel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Proceso Electoral");

        jLabel1.setText("ID");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de proceso(*)");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Presidencial", "2- Regional", "3- Distrital", "4- Otros" }));
        jComboBox1.setToolTipText("");

        jLabel3.setText("Fecha del proceso(*) (dd/mm/yyyy)");

        jLabel4.setText("Cantidad de votantes periodo anterior (*)");

        jLabel5.setText("Porcentaje mínimo (%)(*)");

        jLabel6.setText("Inicio de registro (*)");

        jLabel7.setText("Fin de registro(*)");

        jLabel9.setText("Fin de validación(*)");

        jLabel8.setText("Inicio de validación(*)");

        jLabel12.setText("Nombre de proceso (*)");

        jTextField9.setEditable(false);

        btnRegister.setText("Registrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnUpdate.setText("Modificar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText("Dar de baja");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jButton1.setText("Agregar Ubigeo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Tipo de proceso", "Fecha de proceso"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setText("Inicio de recepción extra");

        jLabel11.setText("Fin de recepción extra");

        jLabel13.setText("Inicio de validación extra");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jLabel14.setText("Fin de validación extra");

        jLabel15.setText("Inicio de recepcion");

        jLabel16.setText("Fin de recepcion");

        jLabel17.setText("Fechas de Registro");

        jLabel18.setText("Fechas de Validacion");

        jLabel19.setText("Fechas de Recepcion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator5)
                        .addComponent(jSeparator3)
                        .addComponent(jSeparator1)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(176, 176, 176))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(161, 161, 161)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(137, 137, 137))
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(23, 23, 23)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                .addComponent(jTextField1)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                            .addComponent(jTextField14, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel11)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel14)
                                .addComponent(jLabel16)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField4)
                                .addComponent(jTextField8)
                                .addComponent(jTextField2)
                                .addComponent(jTextField11)
                                .addComponent(jComboBox1, 0, 158, Short.MAX_VALUE)
                                .addComponent(jTextField6)
                                .addComponent(jTextField15)
                                .addComponent(jTextField13)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel17)
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnRegister)
                    .addComponent(btnUpdate)
                    .addComponent(btnCancel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        try {
            String name = jTextField1.getText().trim();
             String processtype= (String)jComboBox1.getSelectedItem();
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            Date date = formatter.parse(jTextField2.getText().trim());
            Date startregistrationdate=formatter.parse(jTextField5.getText().trim());
            Date endregistrationdate=formatter.parse(jTextField4.getText().trim());
            Date startvaldationdate=formatter.parse(jTextField7.getText().trim());
            Date endvalidationdate=formatter.parse(jTextField6.getText().trim());

            Date startextrareceptiondate=formatter.parse(jTextField10.getText().trim());
             Date startextravalidationdate=formatter.parse(jTextField12.getText().trim());
             Date startreceptiondate=formatter.parse(jTextField14.getText().trim());
             Date endextrareceptiondate=formatter.parse(jTextField11.getText().trim());
             Date endextravalidationdate=formatter.parse(jTextField13.getText().trim());   
             Date endreceptiondate=formatter.parse(jTextField15.getText().trim());
             
            long idUser = 3;
            User user = Manager.queryUserById(idUser);
          
            long idElectoralProcess= Integer.parseInt(jTextField9.getText().trim());
            ElectoralProcess process = Manager.queryElectoralProcessById(idElectoralProcess);
            process.setDate(date);
            process.setName(name);
            process.setStartExtraReceptionDate(startextrareceptiondate);
            process.setStartExtraValidationDate(startextravalidationdate);
            process.setStartReceptionDate(startreceptiondate);
            process.setEndExtraReceptionDate(endextrareceptiondate);
            process.setEndExtraValidationDate(endextravalidationdate);
            process.setEndReceptionDate(endreceptiondate);
            process.setUser(user);
            process.setStatus("Activo");
            ProcessType proctype;
            proctype=  Manager.queryProcessTypeById(Long.parseLong(processtype.substring(0,1)));
            process.setProcessType(proctype);
             process.setStartValidationDate(startvaldationdate);
            process.setEndValidationDate(endvalidationdate);
            process.setStartRegistrationDate(startregistrationdate);
            process.setEndRegistrationDate(endregistrationdate);
            long id = Long.parseLong(jTextField9.getText().trim());
            process.setId(id);
            
            int val=validation(name,processtype, date , startregistrationdate,
                    endregistrationdate,  startvaldationdate,endvalidationdate, startextrareceptiondate, 
                    startextravalidationdate,startreceptiondate,endextrareceptiondate, 
                    endextravalidationdate,  endreceptiondate);
            try{                       
             if(Integer.parseInt(jTextField3.getText())>0){
            Integer countprevious=Integer.parseInt(jTextField3.getText());
            process.setPopulation(countprevious);
             }else{
                JOptionPane.showMessageDialog(this, "Cantidad de votantes debe ser mayor a cero", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
             if(Double.parseDouble(jTextField8.getText())>0 && Double.parseDouble(jTextField8.getText())<1 && val==0){
                 Double minpercent= Double.parseDouble(jTextField8.getText());
                 process.setMinPercentage(minpercent);
                 updateElectoralProcess(process);
                 JOptionPane.showMessageDialog(this, "El proceso electoral ha sido actualizado");
                 refreshTblElectoralProcess();
             }else if (Double.parseDouble(jTextField8.getText())<0 || Double.parseDouble(jTextField8.getText())>1){
                JOptionPane.showMessageDialog(this, "El porcentaje debe ser mayor a cero y menor a 1", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
            
            
            }catch (NumberFormatException ex) {
           //  Logger.getLogger(ElectoralProcess.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No debe contener caracteres la cantidad de votantes o el porcentaje minimo", "Alerta", JOptionPane.WARNING_MESSAGE);
            } 
                         
        }catch (ParseException ex) {
            //  Logger.getLogger(ElectoralProcess.class.getName()).log(Level.SEVERE, null, ex);					e.printStackTrace();
        }
        


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        JFrame frame1 = null;
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(frame1, "¿Está seguro?");
        if (res == JOptionPane.OK_OPTION) {
            try {
                deleteElectoralProcess(Integer.parseInt(jTextField9.getText()));
                
                refreshTblElectoralProcess();
                //jTable2.clear();
                //jTable2.addAll(tableQuery.getResultList());
            } catch (NumberFormatException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            }
            //	refreshTblSalesmans();
        }
    }//GEN-LAST:event_btnCancelActionPerformed
public int validation(String name, String processtype, Date date , Date startregistrationdate,
        Date endregistrationdate, Date startvaldationdate,Date endvalidationdate, Date startextrareceptiondate, 
        Date startextravalidationdate,Date startreceptiondate,Date endextrareceptiondate, 
        Date endextravalidationdate, Date endreceptiondate){
     if (name.trim().length()==0 || date==null ||startregistrationdate==null || endregistrationdate==null ||
         startvaldationdate==null || endvalidationdate==null ||  startreceptiondate==null     ||
          endreceptiondate==null ){
         JOptionPane.showMessageDialog(this, "Completar campos obligatorios (*)", "Alerta", JOptionPane.WARNING_MESSAGE);
         return 1;
     }    
     if (date.before(startregistrationdate)){
          JOptionPane.showMessageDialog(this, "El proceso debe ser creado antes de empezar con la etapa de registro", "Alerta", JOptionPane.WARNING_MESSAGE);
         return 1;
     }
     if (date.before(startvaldationdate)){
          JOptionPane.showMessageDialog(this, "El proceso debe ser creado antes de empezar con la etapa de validación", "Alerta", JOptionPane.WARNING_MESSAGE);
         return 1;
     }
     if (date.before(startreceptiondate)){
          JOptionPane.showMessageDialog(this, "El proceso debe ser creado antes de empezar con la etapa de recepción", "Alerta", JOptionPane.WARNING_MESSAGE);
         return 1;
     }
     if (startreceptiondate.before(endreceptiondate)==false){
          JOptionPane.showMessageDialog(this, "Rango de fechas de recepción inválido", "Alerta", JOptionPane.WARNING_MESSAGE);
         return 1;
     }
     if (startvaldationdate.before(endvalidationdate)==false){
          JOptionPane.showMessageDialog(this, "Rango de fechas de validación inválido", "Alerta", JOptionPane.WARNING_MESSAGE);
         return 1;
     }
      if (startregistrationdate.before(endregistrationdate)==false){
          JOptionPane.showMessageDialog(this, "Rango de fechas de registro inválido", "Alerta", JOptionPane.WARNING_MESSAGE);
         return 1;
     }
       if (endreceptiondate.before(startvaldationdate)==false){
          JOptionPane.showMessageDialog(this, "Las fechas de recepción deben ser antes de la validación", "Alerta", JOptionPane.WARNING_MESSAGE);
         return 1;
     }
        if (endregistrationdate.before(startvaldationdate)==false){
          JOptionPane.showMessageDialog(this, "Las fechas de registro deben ser antes de la validación", "Alerta", JOptionPane.WARNING_MESSAGE);
         return 1;
     }
        
     
     
     else return 0;
  }
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:

       try {
            String name = jTextField1.getText().trim();
             String processtype= (String)jComboBox1.getSelectedItem();
            SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
            Date date = formatter.parse(jTextField2.getText().trim());
            Date startregistrationdate=formatter.parse(jTextField5.getText().trim());
            Date endregistrationdate=formatter.parse(jTextField4.getText().trim());
            Date startvaldationdate=formatter.parse(jTextField7.getText().trim());
            Date endvalidationdate=formatter.parse(jTextField6.getText().trim());

            Date startextrareceptiondate=formatter.parse(jTextField10.getText().trim());
             Date startextravalidationdate=formatter.parse(jTextField12.getText().trim());
             Date startreceptiondate=formatter.parse(jTextField14.getText().trim());
             Date endextrareceptiondate=formatter.parse(jTextField11.getText().trim());
             Date endextravalidationdate=formatter.parse(jTextField13.getText().trim());   
             Date endreceptiondate=formatter.parse(jTextField15.getText().trim());
               
            long idUser = 3;
             java.lang.System.out.println(jTextField1.getText().trim());
            User user = Manager.queryUserById(idUser);
            ElectoralProcess process = new ElectoralProcess();
            
            process.setDate(date);
            process.setName(name);
            process.setStartExtraReceptionDate(startextrareceptiondate);
            process.setStartExtraValidationDate(startextravalidationdate);
            process.setStartReceptionDate(startreceptiondate);
            process.setEndExtraReceptionDate(endextrareceptiondate);
            process.setEndExtraValidationDate(endextravalidationdate);
            process.setEndReceptionDate(endreceptiondate);
            process.setStage(-1);
            process.setStatus("Activo");
            process.setUser(user);
            ProcessType proctype;
            proctype=  Manager.queryProcessTypeById(Long.parseLong(processtype.substring(0,1)));
            process.setProcessType(proctype);
             process.setStartValidationDate(startvaldationdate);
            process.setEndValidationDate(endvalidationdate);
            process.setStartRegistrationDate(startregistrationdate);
            process.setEndRegistrationDate(endregistrationdate);
            try{                       
             if(Integer.parseInt(jTextField3.getText())>0){
            Integer countprevious=Integer.parseInt(jTextField3.getText().trim());
            process.setPopulation(countprevious);
             }else{
                JOptionPane.showMessageDialog(this, "Cantidad de votantes debe ser mayor a cero", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
             int val=validation(name,processtype, date , startregistrationdate,
         endregistrationdate,  startvaldationdate,endvalidationdate, startextrareceptiondate, 
        startextravalidationdate,startreceptiondate,endextrareceptiondate, 
         endextravalidationdate,  endreceptiondate);
             if(Double.parseDouble(jTextField8.getText())>0 && Double.parseDouble(jTextField8.getText())<1 && val==0 ){
                 Double minpercent= Double.parseDouble(jTextField8.getText());
                 process.setMinPercentage(minpercent);
                   java.lang.System.out.println(jTextField1.getText());
                  addElectoralProcess(process);
                 JOptionPane.showMessageDialog(this, "Proceso electoral creado");
                  refreshTblElectoralProcess();
                 
             }else if (Double.parseDouble(jTextField8.getText())<0 || Double.parseDouble(jTextField8.getText())>1){
                JOptionPane.showMessageDialog(this, "El porcentaje debe ser mayor a cero y menor a 1", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
            }catch (NumberFormatException ex) {
           //  Logger.getLogger(ElectoralProcess.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "No debe contener caracteres la cantidad de votantes o el porcentaje minimo", "Alerta", JOptionPane.WARNING_MESSAGE);
            }                      
        }catch (ParseException ex) {
            //  Logger.getLogger(ElectoralProcess.class.getName()).log(Level.SEVERE, null, ex);					e.printStackTrace();
        }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        long idElectoralProcess=Long.parseLong(jTextField9.getText().trim());
         new ZoneGui(idElectoralProcess).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int selRow = jTable1.getSelectedRow();
				long processId = Long.parseLong(
						jTable1.getValueAt(selRow, 0).toString());
				ElectoralProcess p = Manager.queryElectoralProcessById(processId);
                                jTextField9.setText("" + p.getId());
                                jTextField1.setText(p.getName());
                                jTextField3.setText(""+p.getPopulation());
                                jTextField8.setText(""+p.getMinPercentage());
                                jComboBox1.setSelectedItem(p.getProcessType());
                                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");                                                                
                                jTextField2.setText(""+ formatter.format(p.getDate()));
                                jTextField5.setText(""+formatter.format(p.getStartRegistrationDate()));
                                jTextField4.setText(""+formatter.format(p.getEndRegistrationDate()));
                                jTextField7.setText(""+formatter.format(p.getStartValidationDate()));
                                jTextField6.setText(""+formatter.format(p.getEndValidationDate()));
                                jTextField10.setText(""+formatter.format(p.getStartExtraReceptionDate()));
                                jTextField12.setText(""+formatter.format(p.getStartExtraValidationDate()));
                                jTextField14.setText(""+formatter.format(p.getStartReceptionDate()));
                                jTextField11.setText(""+formatter.format(p.getEndExtraReceptionDate()));
                                jTextField13.setText(""+formatter.format(p.getEndExtraValidationDate()));
                                jTextField15.setText(""+formatter.format(p.getEndReceptionDate()));
                                java.lang.System.out.println("Partido seleccionado");
                           java.lang.System.out.println("Proceso Electoral seleccionado");
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElectoralProcessGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElectoralProcessGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElectoralProcessGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElectoralProcessGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElectoralProcessGui().setVisible(true);
            }
        });
    }
    class MyTableModel extends AbstractTableModel {
        ArrayList<Model.ElectoralProcess> electoralProcessList = Manager.queryAllElectoralProcess();
		String [] titles = {"Id", "Nombre", "Tipo Proceso","Fecha Proceso"};
		public int getColumnCount() {
			// TODO Auto-generated method stub
			return 4;
		}

		public int getRowCount() {
			// TODO Auto-generated method stub
			return electoralProcessList.size();
		}

		public Object getValueAt(int row, int col) {
			// TODO Auto-generated method stub
			String value = "";
			switch (col) {
                        case 0:
				value = "" + electoralProcessList.get(row).getId();
				break;
			case 1:
				value = "" + electoralProcessList.get(row).getName();
				break;
			case 2:
				value = "" + electoralProcessList.get(row).getProcessType().getName();
				break;
			case 3:
				value = "" + new SimpleDateFormat("dd/MM/yyyy").format(electoralProcessList.get(row).getDate());
				break;			
			}
			return value;
		}
		public String getColumnName(int col){
			return titles[col];
		}
    }
    public void refreshTblElectoralProcess() {
		electoralProcessModel.electoralProcessList = Manager.queryAllElectoralProcess();
		electoralProcessModel.fireTableChanged(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
